### ISSUE TITLE
[feature request] additionnal lvars (chronometer)

### ISSUE THREAD

**Issue by Delta-Charlie-DEV** [Fragtality/FenixQuartz#13]
Hi @Fragtality , 
again, many thanks for your tool, and the latest update works like a charm (direct LVARs integration).

I've setup a bunch of instruments for Air Manager thanks to you :
https://github.com/Delta-Charlie-DEV/A320FENIX_AIRMANAGER

Do you plan to add additional Lvars for other instruments ? For example the clock / chrono displays on the front panel ?

**Comment by Fragtality** [comment]
The Clock is a definitive "No"! Since the Chrono is always synced to the Simulator Time, the Time/Display can easily be assembled with the standard Offsets / SimVars. No need to read that from Memory.

CHR / ET maybe yes, tendency no:
1) No real need to have it directly accessible on the StreamDeck (that is still the main Purpose of the Tool), it is not something that needs to be intermediately accessible imho.
2) My current Focus is more on getting the current Values as stable as possible, especially really really important Stuff like the FCU and RMP.
CHR/ET do not really stop or impede anyone when flying the Fenix in more demanding Situations (like VATSIM/IVAO e.g.).

I'll keep an Eye on it - if these Values are easy to find and there is an reliable Way to access them, I can add them in the Future. But I honestly will not invest much Time in that. I have other Tools for the Fenix in my Mind which contribute more to the Experience than having the CHR/ET ;)

**Comment by Fragtality** [comment]
Try the latest Build and tell me how it works for you :wink:
https://github.com/Fragtality/FenixQuartz/raw/master/FenixQuartz-latest.zip

**Comment by Delta-Charlie-DEV** [comment]
Fantastic :-)
![image](https://user-images.githubusercontent.com/76492436/227656522-508b7b45-d0c3-4d7c-b277-2dd210970163.png)

**Comment by Delta-Charlie-DEV** [comment]
BTW what does the variable "ooMode" in FenixQuartz.dll.config do ?

 <add key="ooMode" value="false"/>

**Comment by Fragtality** [comment]
Changes the VS Output to have "oo". So "-400" will be displayed as "-4oo" instead.
(Only relevant to String-Mode and Offsets)
