### ISSUE TITLE
Dear Fragtality The Feinx v1.5.1.200 v-speed Lvar unable to access data

### ISSUE THREAD

**Issue by uu373** [Fragtality/FenixQuartz#16]
Dear Fragtality The Feinx v1.5.1.200 v-speed Lvar unable to access data,  could you help me to verify that? Thank you.

Best regards.
Zeng

**Comment by uu373** [comment]
Sorry, I didn't describe it well.

V-speed Lvar loses data (cannot be synchronised) when changes are made to the S_FCU_VERTICAL_SPEED variable. In the FenixQuartz UI you can see normal data, but the Lvar does not change and stays at 0.

**Comment by Fragtality** [comment]
V-Speeds are V-Speeds (V1, VR, V2). Vertical-Speed is Vertical-Speed.

There are no Reports about Vertical-Speed not working in any Output Variant, so very likely you're doing something wrong.
Have you actually try *flying* the Fenix? Vertical-Speed does not work on all Situations when on Ground.

**Comment by uu373** [comment]
Yes, I test flew the Fenix and after using the S_FCU_VERTICAL_SPEED variable (Vs Pull Push), the vertical speed is out of sync with FNX2PLD_fcuVs. Profile settings are the same as v1.0.6.146.

Viewing in the FenixQuartz UI there is Vertical-Speed data, but FNX2PLD_fcuVs is always 0. I'm not sure where the problem is.

**Comment by Fragtality** [comment]
And you use that Switch the correct Way?
Increase by 1 for Pull, Decrease by 1 for Push?

**Comment by uu373** [comment]
Yes, that's right.

**Comment by Fragtality** [comment]
Made a Quick-Test, saw no Issue with the L-Var.
You are aware that it Zero when the Display is Dashed, right?

**Comment by uu373** [comment]
Yes, I know it's zero when it shows the dashed line.

It's when I pushed and pulled the Vs when it showed Dashed that the FNX2PLD_fcuVs stopped syncing the data. I trigger this bug every time I do this.

Is there a clean version of the memory read data project I can refer to? Yours is too complicated I don't know c# and have a rather average level of programming. It would be nice if there was a module written in c++ or just for reading data from memory, this would be very helpful for me. Thank you very much.

**Comment by Fragtality** [comment]
You can't read C# but want a Module in C++?! A C++ Module/Version will never come.

The Data is as clean as it can be. It is converted to FPA if needed and is written to the L-Var. Well it is also selected from which Memory-Location to read - which is something internal and it is not planned to change anything about that (because no one but you would want that).

Since your monitoring the Debug-UI - what is "isAltVsMode" reporting? It should be true when VS is active (that is in the FMA).

**Comment by Fragtality** [comment]
Don't know, just works. Even when I push the VS Knob.

Maybe share the Logs. If that should be really something with FenixQuartz, it may give a Hint.

**Comment by uu373** [comment]
I flew it a few more times on test flights and now it looks like the data in the air is normal.

On the ground as you said it can't adapt to all situations, he is not able to synchronise with its Vertical-Speed, can this be solved please? If it can be solved that would be great.
![Image](https://github.com/Fragtality/FenixQuartz/assets/135104552/17e08858-dc95-481f-95d7-0e8b9bf99f29)

**Comment by Fragtality** [comment]
Are you kidding me ?!?

To summarize:
- It is like it is, I had to make a Decision - and that was to make it accurate in the Air because .... one does not need VERTICAL Speed when being on the GROUND. Because you're neither *climbing* nor *descending* on the Ground.
- So you tested something I specifically warned about in the Readme. You ignored that and reported it as a Bug.
- Even then, when specifically pointed to not test that on the Ground, you continued to ignore that.
- Demanding such Simulation-Accuracy while running with full "Xbox/Game UI" is a Joke in itself.
