### ISSUE TITLE
FCU outputs for saitek Multi panel with Spad

### ISSUE THREAD

**Issue by Juanitalinc** [Fragtality/FenixQuartz#23]
Hi there,

would like to know if someone find a solution for the ALT , VS , HDG and SPD value on the Saitek Multi panel with Spadnext. 
Which are the LVars to insert in Spad ? 

Thanks !!! 

![image](https://github.com/Fragtality/FenixQuartz/assets/150169235/ebb75393-6ce8-4a1f-83d4-f3d9bb106ccd)

**Comment by rickvandijck** [comment]
All the LVAR’s are in “Assignments.txt”

**Comment by Fragtality** [comment]
Yes, but only if the Raw- and Lvar-Mode are enabled - the Assignments File only reflects the current Configuration. And FenixQuartz defaults to output pre-formatted Strings as FSUIPC Offsets.

https://github.com/Fragtality/FenixQuartz#usage-with-other-3rd-party-tools
https://github.com/Fragtality/FenixQuartz#configuration

**Comment by Fragtality** [comment]
Well, that is a very possible Result.
You did not download the Release Package and put it in a Place not recommended.

Guess it easier if you just test the current Dev-Build which includes an Installer ;)
https://www.mediafire.com/file/3ll6wft3m3k64tl/FenixQuartz-Installer-v1.2.0.exe/file

**Comment by Juanitalinc** [comment]
ok i's installed and i change raw values and uselvars in "true"
but right now i lost the "assignement" file !! 

![image](https://github.com/Fragtality/FenixQuartz/assets/150169235/ae6167c0-55d3-4ec5-8fd6-76cdcc9975d9)

**Comment by Fragtality** [comment]
Sure?

It is located in the same Folder as the config File: %appdata%\FenixQuartz

**Comment by Juanitalinc** [comment]
ok yes it appears !! thanks anr right now do you know where i can add them to spadnext ? 
![image](https://github.com/Fragtality/FenixQuartz/assets/150169235/ca24db85-2e8b-4485-8c3b-390b42b4feb3)

**Comment by Juanitalinc** [comment]
i'm working on this but nothing appears in my multi panel

**Comment by Fragtality** [comment]
Don't ask me anything about Spad.next - I don't know anything about it.

You get the raw numeric Values via L-Vars, it is up to you and your Hardware how you apply the necessary Logic and Format.

**Comment by Fragtality** [comment]
I can only tell you, based on what I've heard from Users in the MobiFlight Community that some use the default String-Mode (with some trimming/substringing afaik) because it applies the necessary Logic and Format and thus is easier for some.

Example on Heading: on String-Mode the Value is automatically formatted to 3 Digits (i.e. Heading 005 instead of 5) and the Dashed and Managed State are also already applied (i.e. the String will be ---\*, or 005* instead of you having to evaluate the L-Var from Fenix2GSX for the Dashed State and the L-Var from Fenix for the Managed State)

**Comment by Juanitalinc** [comment]
Man all it's working !! thnaks a lot for your help !!!! :)

**Comment by Fragtality** [comment]
Sure, no Problem.

Btw: That what is intended to be download and installed is located under [Releases](https://github.com/Fragtality/FenixQuartz/releases). Don't clone the Repository ("Download ZIP") - holds true for most GitHub Projects!

Also please redownload Version 1.2 if it is released there. You basically got a "Release Candidate" where I don't know if there will be further Changes/Fixes or not!

**Comment by Juanitalinc** [comment]
I will !! but yeahh great !! have a good night (if you are in europe )

**Comment by Fragtality** [comment]
Don't get on my nerves with that. Or Fenix' nerves. miniCockpit is the Problem. They don't deliver.

As you know very well yourself there is a Tool which would provide the FCU Display Values. There are other FCUs which work fully with the Fenix (SimpleFCU, custom-builds). miniFCU even comes with a Software which obviously is able to read L-Vars.
So ask them why they are unable to test the existence of some Variables and if present use them. 🤷‍♂️

**Comment by Juanitalinc** [comment]
So for now, as long as they don't do anything, we can't do anything on our end to read these display values ?

**Comment by Fragtality** [comment]
They had promised Spad.next and Mobiflight Support. Which is not there yet. Even without any Timeline by now.
Both Softwares would not even be needed for the Fenix, since their already existing Software (already capable of reading L-Vars) would just need to read the L-Vars of FenixQuartz.

So please don't waste my Time with these Questions. I don't have a miniFCU, I won't have a miniFCU. I prefer flexible and true-mouse-free Solutions over such specialized Boxes (regardless how good they are made, which it is). So don't ask me Questions about Things *you* should now better than me.

**Comment by Juanitalinc** [comment]
ok thanks and sorry for asking so .

**Comment by Fragtality** [comment]
Np. Sorry if it was a bit harsh, but I follow these miniFCU Discussions from Day 1 it was announced. Very well knowing that it could just work with the Fenix. But yet no one builds up Pressure on miniCockpit to make it happen.

I would be open if they would approach me. In Fact most Additions/Changes to FenixQuartz where to improve 3rd Party Software/Hardware Support
